#!/bin/bash

# change this to the directory of where you built rustc for xtensa
CUSTOM_RUSTC=$(dirname $(readlink -e $0))/../rust-xtensa

export RUST_BACKTRACE=1 
export XARGO_RUST_SRC=$CUSTOM_RUSTC/library # or /src for an older compiler
export RUSTC=$CUSTOM_RUSTC/build/x86_64-unknown-linux-gnu/stage2/bin/rustc
export RUSTDOC=$CUSTOM_RUSTC/build/x86_64-unknown-linux-gnu/stage2/bin/rustdoc
export PATH=$PATH:$HOME/.platformio/packages/toolchain-xtensa32/bin/
export PATH=$PATH:$HOME/.platformio/packages/toolchain-xtensa/bin/
